spring:
  cloud:
    stream:
      bindings:
        input: hdfs.data
  hadoop:
    fsUri: hdfs://borneo:8020
  redis:
    host: borneo
---

spring:
  profiles: cloud
  hadoop:
    fsUri: ${vcap.services.hadoop.credentials.fs.defaultFS:hdfs://localhost:8020}
---
