spring:
  batch:
    job:
      enabled: false
  hadoop:
    fsUri: hdfs://borneo:8020
    resourceManagerHost: borneo
demo:
  inputDir: /demo/hashtags/input
  inputFileName: tweets.dat
  inputLocalDir: data
  outputDir: /demo/hashtags/output
  sparkAssembly: hdfs:///app/spark/spark-assembly-1.5.0-hadoop2.6.0.jar
